### ISSUE TITLE
NPE Listener#onMessageReceived:45

### ISSUE THREAD

**Issue by ducc** [ducc/JavaMusicBot#10]
```
[08:23:46] [Fatal] [JDA]: One of the EventListeners had an uncaught exception
[08:23:46] [Fatal] [JDA]: Encountered an exception:
[08:23:46] [Fatal] [JDA]: java.lang.NullPointerException
        at ovh.not.javamusicbot.Listener.onMessageReceived(Listener.java:45)
        at net.dv8tion.jda.core.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:319)
        at net.dv8tion.jda.core.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:64)
        at net.dv8tion.jda.core.handle.MessageCreateHandler.handleDefaultMessage(MessageCreateHandler.java:125)
        at net.dv8tion.jda.core.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:47)
        at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:38)
        at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:688)
        at net.dv8tion.jda.core.requests.WebSocketClient.onTextMessage(WebSocketClient.java:437)
        at com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:352)
        at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:262)
        at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:240)
        at com.neovisionaries.ws.client.ReadingThread.handleTextFrame(ReadingThread.java:965)
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:748)
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:110)
        at com.neovisionaries.ws.client.ReadingThread.run(ReadingThread.java:66)
```

**Comment by ducc** [comment]
Related to https://github.com/ducc/BorkedJavaMusicBot/issues/7

**Comment by ducc** [comment]
Exception is no longer valid
