### ISSUE TITLE
java.util.UnknownFormatConversionException: Conversion = 'p'

### ISSUE THREAD

**Issue by ducc** [ducc/JavaMusicBot#19]
```
[08:20:36] [Fatal] [JDA]: java.util.UnknownFormatConversionException: Conversion = 'p'
        at java.util.Formatter$FormatSpecifier.conversion(Formatter.java:2691)
        at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2720)
        at java.util.Formatter.parse(Formatter.java:2560)
        at java.util.Formatter.format(Formatter.java:2501)
        at java.util.Formatter.format(Formatter.java:2455)
        at java.lang.String.format(String.java:2940)
        at ovh.not.javamusicbot.command.ChooseCommand.on(ChooseCommand.java:42)
        at ovh.not.javamusicbot.Listener.onMessageReceived(Listener.java:63)
        at net.dv8tion.jda.core.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:381)
        at net.dv8tion.jda.core.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:84)
        at net.dv8tion.jda.core.handle.MessageCreateHandler.handleDefaultMessage(MessageCreateHandler.java:129)
        at net.dv8tion.jda.core.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:50)
        at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:38)
        at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:738)
        at net.dv8tion.jda.core.requests.WebSocketClient.onTextMessage(WebSocketClient.java:475)
```

**Comment by ducc** [comment]
Fixed in c38d123
