### ISSUE TITLE
Handle bad radio streams

### ISSUE THREAD

**Issue by ducc** [ducc/JavaMusicBot#22]
```
[lava-daemon-pool-playback-77-thread-4] ERROR com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor - Error in playback of http://uk1.internet-radio.com:8130/
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:40)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:102)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Mp3 frame not found.
        at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3FrameReader.runFrameScanLoop(Mp3FrameReader.java:77)
        at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3FrameReader.scanForFrame(Mp3FrameReader.java:53)
        at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3TrackProvider.parseHeaders(Mp3TrackProvider.java:72)
        at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3AudioTrack.process(Mp3AudioTrack.java:33)
        at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:27)
        at com.sedmelluq.discord.lavaplayer.source.http.HttpAudioTrack.process(HttpAudioTrack.java:51)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:90)
        ... 4 more
```

**Comment by ducc** [comment]
Support staff are dealing with these when reported & https://github.com/ducc/JavaMusicBot/commit/389ce8d218bccd4abe4b211c3afe7a15d06732df should make it easy to find broken streams faster
